import type { Metadata } from "next";

import Footer from "@/components/common/footer";
import Navbar from "@/components/common/navbar";

export const metadata: Metadata = {
  title: "Inkara",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="h-full md:h-screen flex flex-col ">
      <Navbar />
      <main className=" ">{children}</main>
      <div className="flex flex-col grow justify-end">
        <Footer />
      </div>
    </div>
  );
}
